import Footer from "@/components/footer/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import ClientOnly from "@/providers/Client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          {children}
          <Footer />
        </ClientOnly>
      </body>
    </html>
  );
}
